language: php
dist: trusty
php:
  - 7
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

env:
  matrix:
    - LOWEST_DEPS=""
    - LOWEST_DEPS="--prefer-lowest"

services:
  - mysql

sudo: false

before_script:
  # - mysql -e 'create database sabredav'
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini  
  # - composer self-update
  - composer update --prefer-source $LOWEST_DEPS

script:
    - find Core -name "*.php" | xargs -n1 php -l 
    - ./vendor/bin/sabre-cs-fixer fix . --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache
