baikal_frontend_homepage:
    pattern:  /
    defaults: { _controller: BaikalFrontendBundle:Dashboard:index }

baikal_frontend_calendar_list:
    pattern:  /calendars
    defaults: { _controller: BaikalFrontendBundle:Calendar/List:index }

baikal_frontend_calendar_list_delete:
    pattern:  /calendars/{calendar}/delete
    defaults: { _controller: BaikalFrontendBundle:Calendar/List:delete }

baikal_frontend_calendar_instructions:
    pattern:  /calendars/{calendar}/instructions
    defaults: { _controller: BaikalFrontendBundle:Calendar/Instructions:index }

baikal_frontend_calendar_form_new:
    pattern:  /calendars/new
    defaults: { _controller: BaikalFrontendBundle:Calendar/Form:new }

baikal_frontend_calendar_form_edit:
    pattern:  /calendars/{calendar}
    defaults: { _controller: BaikalFrontendBundle:Calendar/Form:edit }

baikal_frontend_calendar_view:
    pattern:  /calendars/{calendar}/view
    defaults: { _controller: BaikalFrontendBundle:Calendar/View:index }

baikal_frontend_calendar_view_fullscreen:
    pattern:  /calendars/{calendar}/view/fullscreen
    defaults: { _controller: BaikalFrontendBundle:Calendar/View:fullscreen }

baikal_frontend_addressbook_list:
    pattern:  /addressbooks
    defaults: { _controller: BaikalFrontendBundle:Addressbook/List:index }

baikal_frontend_addressbook_list_delete:
    pattern:  /addressbooks/{addressbook}/delete
    defaults: { _controller: BaikalFrontendBundle:Addressbook/List:delete }

baikal_frontend_addressbook_view:
    pattern:  /addressbooks/{addressbook}/view
    defaults: { _controller: BaikalFrontendBundle:Addressbook/View:index }

baikal_frontend_addressbook_form_new:
    pattern:  /addressbooks/new
    defaults: { _controller: BaikalFrontendBundle:Addressbook/Form:new }

baikal_frontend_addressbook_form_edit:
    pattern:  /addressbooks/{addressbook}/edit
    defaults: { _controller: BaikalFrontendBundle:Addressbook/Form:edit }

baikal_frontend_profile:
    pattern:  /profile
    defaults: { _controller: BaikalFrontendBundle:Profile:index }

baikal_frontend_login:
    pattern: /login
    defaults: { _controller: BaikalFrontendBundle:Auth:loginform }

baikal_frontend_login_check:
    pattern: /login_check
    # no controller, symfony intercepts this

baikal_frontend_logout:
    pattern: /logout
    # no controller, symfony intercepts this

baikal_frontend_oauth_login:
    pattern: /oauth/v2/auth/login
    defaults: { _controller: BaikalFrontendBundle:Auth:oauthloginform }

baikal_frontend_oauth_login_check:
    pattern: /oauth/v2/auth/login_check
    # no controller, symfony intercepts this