baikal_admin:
    resource: "@BaikalAdminBundle/Resources/config/routing.yml"
    prefix: /admin

baikal_davservices:
    resource: "@BaikalDavServicesBundle/Resources/config/routing.yml"
    prefix: /dav

baikal_rest_api:
    resource: "@BaikalRestBundle/Resources/config/routing.restapi.yml"
    prefix: /api/v1/
    type: rest

baikal_rest_webapi:
    resource: "@BaikalRestBundle/Resources/config/routing.webapi.yml"
    prefix: /webapi/v1/
    type: rest

baikal_frontend:
    resource: "@BaikalFrontendBundle/Resources/config/routing.yml"
    prefix: /

baikal_wellknown:
    resource: "@BaikalWellknownBundle/Resources/config/routing.yml"
    prefix: /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"